Sum square difference
LesliNieto/Ruby-Exercises pull request #8
Opened 2018-10-05 20:04 UTC by LesliNieto

This exercise gets the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

2018-10-05 20:41 UTC, Jucerweb requested changes

2018-10-05 20:41 UTC, Jucerweb commented on squares_sum.rb
> +  ( 1.upto(num).reduce(:+) ** 2 ) - ( 1.upto(num).collect { |num_1| num_1 ** 2 }.sum )
Assign each operation to  a variable, example: 
`sum_of_values = ( 1.upto(num).reduce(:+) ** 2 )`
`sum_of_squares =  1.upto(num).inject(:+) ** 2` and then...
`sum_of_values - sum_of_squares` 
 this makes you method more legible

2018-10-05 20:48 UTC, LesliNieto commented on squares_sum.rb
> +  ( 1.upto(num).reduce(:+) ** 2 ) - ( 1.upto(num).collect { |num_1| num_1 ** 2 }.sum )
You're right.

2018-10-08 21:40 UTC, Jucerweb approved these changes

2018-10-08 21:40 UTC, merged